### ISSUE TITLE
2024.1208.0上使用会导致歌曲结算页面不显示并报错

### ISSUE THREAD

**Issue by ZnCookie** [MATRIX-feather/LLin#13]
附上log
```
2024-12-09 13:13:01 [error]: An unhandled error has occurred.
2024-12-09 13:13:01 [error]: System.MissingMethodException: Method not found: 'System.Nullable`1<Double> osu.Game.Rulesets.Scoring.HitEventExtensions.CalculateUnstableRate(System.Collections.Generic.IEnumerable`1<osu.Game.Rulesets.Scoring.HitEvent>)'.
2024-12-09 13:13:01 [error]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.Data.Gameplay.GameplayValues.FromScore(ScoreInfo scoreInfo)
2024-12-09 13:13:01 [error]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.Tracker.ScreenTracker.onResultsScreen(ResultsScreen results)
2024-12-09 13:13:01 [error]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.Tracker.ScreenTracker.onScreenSwitch(IScreen prevScreen, IScreen nextScreen)
2024-12-09 13:13:01 [error]: at osu.Framework.Screens.ScreenStack.Push(IScreen source, IScreen newScreen)
2024-12-09 13:13:01 [error]: at osu.Framework.Screens.ScreenExtensions.Push(IScreen screen, IScreen newScreen)
2024-12-09 13:13:01 [error]: at osu.Game.Screens.Select.PlaySongSelect.<>c__DisplayClass12_0.<PresentScore>b__0()
2024-12-09 13:13:01 [error]: at osu.Game.Screens.Select.SongSelect.FinaliseSelection(BeatmapInfo beatmapInfo, RulesetInfo ruleset, Action customStartAction)
2024-12-09 13:13:01 [error]: at osu.Game.Screens.Select.PlaySongSelect.PresentScore(ScoreInfo score)
2024-12-09 13:13:01 [error]: at osu.Game.Screens.Select.Leaderboards.BeatmapLeaderboard.<>c__DisplayClass36_0.<CreateDrawableTopScore>b__0()
2024-12-09 13:13:01 [error]: at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
2024-12-09 13:13:01 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
2024-12-09 13:13:01 [error]: at osu.Framework.Input.InputManager.Update()
2024-12-09 13:13:01 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2024-12-09 13:13:01 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-12-09 13:13:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-12-09 13:13:01 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-12-09 13:13:01 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-12-09 13:13:01 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions.
2024-12-09 13:13:01 [verbose]: ⚠️ An unhandled error has occurred.
2024-12-09 13:13:01 [verbose]: 
2024-12-09 13:13:01 [verbose]: This error has been automatically reported to the devs.
```

**Comment by ZnCookie** [comment]
看上去可能是UR算法变动导致的

**Comment by MATRIX-feather** [comment]
感谢报告，但gosu集成在最近的提交里被移除了，因此我没法再提供和此功能有关的支持。

目前可用的解决办法是使用[最新构建](https://github.com/MATRIX-feather/LLin/actions/runs/12009789486)，然后用 [tosu](https://github.com/tosuapp/tosu) 来代替LLin原本的gosu集成
