### ISSUE TITLE
[Player] Method not found: 'Boolean osu.Game.Beatmaps.BeatmapInfo.get_EpilepsyWarning()'

### ISSUE THREAD

**Issue by CloneWith** [MATRIX-feather/LLin#14]
This would prevent the storyboard in Hikariii from loading, and always show the epilepsy warning for every beatmap.

I think it should be the update to be blamed...

```
2024-12-09 14:58:29 [important]: 故事版加载器在加载时出现了问题: Method not found: 'Boolean osu.Game.Beatmaps.BeatmapInfo.get_EpilepsyWarning()'.
2024-12-09 14:58:29 [verbose]: at osu.Game.Rulesets.IGPlayer.Feature.Player.Plugins.Bundle.Storyboard.BackgroundStoryBoardLoader.PostInit()
2024-12-09 14:58:29 [verbose]: at osu.Game.Rulesets.IGPlayer.Feature.Player.Interfaces.Plugins.LLinPlugin.Load()
```

**Comment by MATRIX-feather** [comment]
试试看最新构建，应该能修复这个问题

**Comment by CloneWith** [comment]
解决了🥰
Thx for your prompt reaction!
