### ISSUE TITLE
[Bug] 由于UR算法方法更改签名导致出错

### ISSUE THREAD

**Issue by cdwcgt** [MATRIX-feather/LLin#15]
[1733829337.runtime.log](https://github.com/user-attachments/files/18078539/1733829337.runtime.log)

相关上游更改：
ppy /osu/ pull/30868

```log
2024-12-10 11:20:39 [verbose]: ⚠️ Error occurred while updating tracker ScreenTracker, disabling this...: Method not found: 'System.Nullable`1<Double> osu.Game.Rulesets.Scoring.HitEventExtensions.CalculateUnstableRate(System.Collections.Generic.IEnumerable`1<osu.Game.Rulesets.Scoring.HitE…
2024-12-10 11:20:39 [important]: Error occurred while updating tracker ScreenTracker, disabling this...: Method not found: 'System.Nullable`1<Double> osu.Game.Rulesets.Scoring.HitEventExtensions.CalculateUnstableRate(System.Collections.Generic.IEnumerable`1<osu.Game.Rulesets.Scoring.HitEvent>)'.
2024-12-10 11:20:39 [verbose]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.Data.Gameplay.GameplayValues.FromScore(ScoreInfo scoreInfo)
2024-12-10 11:20:39 [verbose]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.Tracker.ScreenTracker.UpdateValues()
2024-12-10 11:20:39 [verbose]: at osu.Game.Rulesets.IGPlayer.Feature.Gosumemory.TrackerHub.UpdateValues()
```

**Comment by cdwcgt** [comment]
https://github.com/MATRIX-feather/LLin/commit/3249208498746838677caa8012b9f5b792e4985a
难蚌
