### ISSUE TITLE
problem after update to 2024.625.0

### ISSUE THREAD

**Issue by huaji2369** [MATRIX-feather/LLin#5]
更新osu!lazer客户端至2024.625.0版本后出现标题界面无法正常加载的问题
————————以下为lazer客户端捕捉到的错误日志————————
System.MissingMethodException: Method not found: 'Void osu.Game.Screens.Menu.MainMenuButton..ctor(osu.Framework.Localisation.LocalisableString, System.String, osu.Framework.Graphics.Sprites.IconUsage, osuTK.Graphics.Color4, System.Action, Single, osuTK.Input.Key[])'.
at osu.Game.Rulesets.IGPlayer.Helper.Injectors.GameScreenInjector.findButtonSystem(MainMenu menu)
at osu.Game.Rulesets.IGPlayer.Helper.Injectors.GameScreenInjector.onScreenSwitch(IScreen lastscreen, IScreen newscreen)
at osu.Framework.Screens.ScreenStack.Push(IScreen source, IScreen newScreen)
at osu.Framework.Screens.ScreenExtensions.Push(IScreen screen, IScreen newScreen)
at osu.Game.Screens.Menu.IntroScreen.LoadMenu()
at osu.Game.Screens.Menu.IntroTriangles.TrianglesIntroSequence.b__26_4(LazerLogo _)
at osu.Framework.Graphics.Transforms.TransformSequence`1.<>c__DisplayClass33_0.b__0()
at osu.Framework.Graphics.Transforms.TransformSequence`1.osu.Framework.Graphics.Transforms.ITransformSequence.TransformCompleted()
at osu.Framework.Graphics.Transforms.TargetGroupingTransformTracker.<>c.b__13_0(ITransformSequence s)
at osu.Framework.Graphics.Transforms.TargetGroupingTransformTracker.invokePendingRemovalActions()
at osu.Framework.Graphics.Transforms.TargetGroupingTransformTracker.UpdateTransforms(Double& time, Boolean rewinding)
at osu.Framework.Graphics.Transforms.Transformable.updateTransforms(Double time, Boolean forceRewindReprocess)
at osu.Framework.Graphics.Transforms.Transformable.UpdateTransforms()
at osu.Framework.Graphics.Drawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c)
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
at osu.Framework.Platform.GameHost.UpdateFrame()
at osu.Framework.Threading.GameThread.processFrame()

**Comment by MATRIX-feather** [comment]
已修复，可以在[这里](https://github.com/MATRIX-feather/LLin/actions)下载最新构建

因为安卓版构建出了点问题，新版本会迟一两天发

**Comment by Harmskyblue** [comment]
> 已修复，可以在[这里](https://github.com/MATRIX-feather/LLin/actions)下载最新构建
> 
> 因为安卓版构建出了点问题，新版本会迟一两天发

请问构建如何使用，将osu.Game.Rulesets.IGPlayer.csproj和osu.Game.Rulesets.IGPlayer.Tests.csproj放入rulesets中吗，我看rulesets文件夹中的后缀都是dll，这两csproj貌似不太一样

**Comment by MATRIX-feather** [comment]
构建可以参考一下Workflow里的流程，在克隆的根目录下面运行`dotnet publish IGPlayerLoader -c Release`

成功后在 `IGPlayerLoader/bin/Release/net8.0/publish` 下可以找到构建出的dll

**Comment by Harmskyblue** [comment]
> 构建可以参考一下Workflow里的流程，在克隆的根目录下面运行`dotnet publish IGPlayerLoader -c Release`
> 
> 成功后在 `IGPlayerLoader/bin/Release/net8.0/publish` 下可以找到构建出的dll
下载sdk后构建成功了，感谢_(:з)∠)_

**Comment by MATRIX-feather** [comment]
[Done](https://github.com/MATRIX-feather/LLin/releases/tag/2024.625.0)
